### ISSUE TITLE
请问这个报错是什么意思，百度了好久也没解决

### ISSUE THREAD

**Issue by 2762413702** [kusurin/edge-points-tool_win7#1]
![image](https://github.com/kusurin/edge-points-tool_win7/assets/101710154/9a6f84d0-a27d-42af-8a05-f7fe25fbe089)

**Comment by 2762413702** [comment]
已解决，但是现在只用随机数很多搜索好像都会被定义成无效的，作者可以优化一下，比如可以bing搜索随机的古诗，名言警句之类的

**Comment by kusurin** [comment]
现在还是有效的呀，是不是移动设备不行，请去gitee那里下最新的，解决了这个问题
我现在更新一下8
现在好忙xd，可以存个文件然后搜索里面的东西，但是扩充这个库也挺麻烦，所以不搞了w

**Comment by kusurin** [comment]
我自己用的的话是改成了随机加上cas或者gb、iso前缀，但是感觉画蛇添足所以就没提交

**Comment by kusurin** [comment]
如果随机数还是不行的话请告知我，我把这个push上去w

**Comment by 2762413702** [comment]
随机数不行了，我用的时候查询90次实际上能被积分下来的才三次。辛苦作者push一版😊

**Comment by kusurin** [comment]
w吼，我这个还没发现不行，如果（我也）不行的话过几天我整个找古诗什么的，不然就没有什么时间啦，不过可以帮你看看是什么问题

**Comment by TheShadow629** [comment]
> 

![image](https://github.com/kusurin/edge-points-tool_win7/assets/28750354/d9704307-10b6-4db2-bc93-03d0ec82bee0)
![image](https://github.com/kusurin/edge-points-tool_win7/assets/28750354/b6fbd500-0348-4d7e-ad18-dd7a384c9b8d)
只需按照我的写法更改run函数即可实现伪随机古诗句
